server:
  port: 19005
  servlet:
    context-path: /digital-service
spring:
  application:
    name: digital-service
  datasource:
    # 数据源类型:druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_data?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: fMiheeCLOHV1+2z962YFZQ==
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 10
      # 最大连接池数量
      max-active: 20
      # 最小连接池数量
      min-idle: 8
      # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁
      max-wait: 60000
      transaction-query-timeout: 30
      query-timeout: 30
      stat-view-servlet:
        # 是否开启 StatViewServlet
        enabled: true
        # http://ip:port/context-path/druid/index.html
        url-pattern: /druid/*
        # 访问监控页面 白名单，默认127.0.0.1
        allow: 127.0.0.1
        # 访问监控页面 黑名单
        deny: 192.168.10.1
        # 访问监控页面 登陆账号
        login-username: admin
        # 访问监控页面 登陆密码
        login-password: admin
      # WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
      # 是否启用StatFilter默认值false
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
        # session统计
        session-stat-enable: true
        # 最大session数量
        session-stat-max-count: 100000
  # redis配置
  redis:
    host: localhost
    port: 6379
    password: NLws+QIzVElDP8iFBFW1SA==
    # 连接超时时间（毫秒）
    timeout: 1000
    # 设置lettuce连接池需引入 commons-pool2依赖
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
  # ElasticSearch配置
  elasticsearch:
    rest:
      # elasticsearch服务端地址，可配置多个节点
      uris:
        - http://localhost:9200
        - http://localhost:9300
      connection-timeout: 10
      read-timeout: 30
      username: elastic
      password: NLws+QIzVElDP8iFBFW1SA==
  data:
    mongodb:
      # 数据库带权限验证 固定格式：mongodb://用户名:密码@host:port/database name?authSource=admin&authMechanism=SCRAM-SHA-1
      # 数据库无权限验证 固定格式：mongodb://host:port/database name
      #uri: mongodb://root:123456@localhost:27017/e_store?authSource=admin&authMechanism=SCRAM-SHA-1
      uri: Ll5LXDgVgZL0aRMPBomN6bAVxyO3auUFXqbm69sXLbDyfuWZvrlssGhVeNy7FvOuAO7GFkOzxoHJIvyac9BIMQSyq0iPmr91Mc9OA/19qu4tngInhMhM2/gC63svLzyS
      # 设置uri后，以下host等配置无需设置
      #host: localhost
      #port: 27017
      #username: root
      #password: 123456
      #database: e_store
      #authentication-database: admin
mybatis-plus:
  # 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# knife4j配置
knife4j:
  # 开启增强配置
  enable: true
  # 如果为true则开启生产环境屏蔽
  production: false
  basic:
    enable: true
    username: ${spring.application.name}
    password: 123