server:
  port: 19005
  servlet:
    context-path: /digital-service
spring:
  application:
    name: digital-service
  datasource:
    # druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test_data?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: fMiheeCLOHV1+2z962YFZQ==
  # redis配置
  redis:
    host: localhost
    port: 6379
    password: 123456
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
mybatis-plus:
  # 设置Mapper接口所对应的XML文件位置，如果你在Mapper接口中有自定义方法，需要进行该配置
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
# knife4j配置
knife4j:
  # 开启增强配置
  enable: true
  # 如果为true则开启生产环境屏蔽
  production: false
  basic:
    enable: true
    username: ${spring.application.name}
    password: 123